# yaml file to be updated
accounts:
  - name: zhangfei
    domain: shu 
    id: 65
    api_key: ZEVOODE
spring:
    kafka:
        # kafka address
        bootstrap-servers: 127.0.0.1:9200
    redis:
        # host, not address
        host: 127.0.0.1
        # 端口号
        port: 6390
        password: r123kuwy2p
port: 8088
